# Don't edit this file!
# It is automatically updated after every release of https://github.com/47degrees/.github
# If you want to suggest a change, please open a PR or issue in that repository

name: Formatters & Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project (pull-request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2.3.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout project (master)
        if: github.event_name == 'push'
        uses: actions/checkout@v2
      - name: Label PR
        if: github.event_name == 'pull_request'
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
      - name: Setup yq
        run: sudo snap install yq
      - name: Run pre-conditions
        run: test -f .github/actions.yml && eval "$(yq r .github/actions.yml -D "true" pre.ci)" || true
      - name: Run scalafmt on Scala Steward PRs
        if: github.event.pull_request.user.login == '47erbot' && contains(github.event.pull_request.body, 'Scala Steward')
        run: sbt "scalafixEnable; fix" || sbt "scalafmtAll; scalafmtSbt" || true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.5.1
        with:
          commit_message: Run formatter/linter
      - name: Run checks
        run: sbt ci-test
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Run post-conditions
        run: test -f .github/actions.yml && eval "$(yq r .github/actions.yml -D "true" post.ci)" || true
      - name: Automerge Scala Steward PRs
        if: success() && github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'Scala Steward')
        uses: ridedott/merge-me-action@v1.1.36
        with:
          GITHUB_LOGIN: 47erbot
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
